<?php
declare(strict_types=1);
require_once dirname(__DIR__,2).'/config/database.php';
require_once dirname(__DIR__,2).'/includes/auth.php';
require_once dirname(__DIR__,2).'/includes/archive.php';
require_once dirname(__DIR__,2).'/includes/reminder.php';
requireRole(2);
$unit=(int)($_SESSION['unit_id']??0);
if(!$unit){http_response_code(403);
exit('Unit kerja Petugas belum ditetapkan.');
}$errors=[];
$notice='';
$edit=null;
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){if(!verifyCsrfToken())$errors[]='Permintaan tidak valid.';
else{$a=$_POST['action']??'';
$id=(int)($_POST['arsip_id']??0);
if(in_array($a,['create','update'],true)){$v=['no_registrasi'=>trim((string)($_POST['no_registrasi']??'')),'no_surat'=>trim((string)($_POST['no_surat']??'')),'perihal'=>trim((string)($_POST['perihal']??'')),'tanggal_surat'=>(string)($_POST['tanggal_surat']??''),'jenis_surat_id'=>(int)($_POST['jenis_surat_id']??0),'klasifikasi_id'=>(($_POST['klasifikasi_id']??'')===''?null:(int)$_POST['klasifikasi_id']),'rak_id'=>(($_POST['rak_id']??'')===''?null:(int)$_POST['rak_id']),'masa_simpan_tahun'=>(($_POST['masa_simpan_tahun']??'')===''?null:(int)$_POST['masa_simpan_tahun']),'tanggal_mulai_retensi'=>(($_POST['tanggal_mulai_retensi']??'')===''?null:(string)$_POST['tanggal_mulai_retensi']),'tanggal_jatuh_tempo'=>(($_POST['tanggal_jatuh_tempo']??'')===''?null:(string)$_POST['tanggal_jatuh_tempo']),'status_arsip'=>(string)($_POST['status_arsip']??'Aktif'),'detail_arsip'=>trim((string)($_POST['detail_arsip']??''))?:null,'keterangan'=>trim((string)($_POST['keterangan']??''))?:null];
if($v['no_registrasi']===''||$v['no_surat']===''||$v['perihal']===''||$v['tanggal_surat']===''||!$v['jenis_surat_id'])$errors[]='Field wajib belum lengkap.';
if(!in_array($v['status_arsip'],['Aktif','Permanen','Musnah'],true))$errors[]='Status arsip tidak valid.';
if($v['status_arsip']==='Musnah'&&(!$v['masa_simpan_tahun']||!$v['tanggal_mulai_retensi']||!$v['tanggal_jatuh_tempo']))$errors[]='Arsip Musnah wajib memiliki masa simpan dan tanggal retensi/jatuh tempo.';
if($v['status_arsip']==='Permanen'){$v['masa_simpan_tahun']=null;
$v['tanggal_mulai_retensi']=null;
$v['tanggal_jatuh_tempo']=null;
}if($v['rak_id']!==null&&!validArchiveLocation($pdo,$unit,$v['rak_id']))$errors[]='Rak tidak berada pada unit kerja Petugas.';
$s=$pdo->prepare('SELECT arsip_id FROM arsip WHERE no_registrasi=:n AND arsip_id!=:id');
$s->execute(['n'=>$v['no_registrasi'],'id'=>$id]);
if($s->fetch())$errors[]='Nomor registrasi sudah digunakan.';
if(!$errors&&$a==='create'){$pdo->beginTransaction();
try{$sql='INSERT INTO arsip(unit_id,jenis_surat_id,klasifikasi_id,rak_id,no_registrasi,no_surat,perihal,tanggal_surat,masa_simpan_tahun,tanggal_mulai_retensi,tanggal_jatuh_tempo,status_arsip,detail_arsip,keterangan,created_by) VALUES(:unit_id,:jenis_surat_id,:klasifikasi_id,:rak_id,:no_registrasi,:no_surat,:perihal,:tanggal_surat,:masa_simpan_tahun,:tanggal_mulai_retensi,:tanggal_jatuh_tempo,:status_arsip,:detail_arsip,:keterangan,:created_by)';
$pdo->prepare($sql)->execute($v+['unit_id'=>$unit,'created_by'=>(int)$_SESSION['user_id']]);
$newId=(int)$pdo->lastInsertId();
$pdo->prepare('INSERT INTO riwayat_arsip(arsip_id,user_id,aksi,keterangan) VALUES(:a,:u,\'CREATE\',\'Arsip dibuat\')')->execute(['a'=>$newId,'u'=>(int)$_SESSION['user_id']]);
$pdo->commit();
header('Location: arsip.php?edit='.$newId);
exit;
}catch(Throwable $e){$pdo->rollBack();
$errors[]='Data gagal disimpan. Silakan coba lagi.';
}}if(!$errors&&$a==='update'&&$id){$s=$pdo->prepare('UPDATE arsip SET jenis_surat_id=:jenis_surat_id,klasifikasi_id=:klasifikasi_id,rak_id=:rak_id,no_surat=:no_surat,perihal=:perihal,tanggal_surat=:tanggal_surat,masa_simpan_tahun=:masa_simpan_tahun,tanggal_mulai_retensi=:tanggal_mulai_retensi,tanggal_jatuh_tempo=:tanggal_jatuh_tempo,status_arsip=:status_arsip,detail_arsip=:detail_arsip,keterangan=:keterangan WHERE arsip_id=:id AND unit_id=:unit');
$s->execute($v+['id'=>$id,'unit'=>$unit]);
if(!$s->rowCount()){$errors[]='Arsip tidak ditemukan atau di luar unit kerja.';
}else{$pdo->prepare('INSERT INTO riwayat_arsip(arsip_id,user_id,aksi,keterangan) VALUES(:a,:u,\'UPDATE\',\'Arsip diperbarui\')')->execute(['a'=>$id,'u'=>(int)$_SESSION['user_id']]);
$notice='Arsip berhasil diperbarui.';
}}}}}if(isset($_GET['edit'])){$s=$pdo->prepare('SELECT * FROM arsip WHERE arsip_id=:id AND unit_id=:unit');
$s->execute(['id'=>(int)$_GET['edit'],'unit'=>$unit]);
$edit=$s->fetch();
if(!$edit){http_response_code(403);
exit('Arsip tidak dapat diakses.');
}}$jenis=$pdo->query('SELECT jenis_surat_id,nama_jenis FROM jenis_surat ORDER BY nama_jenis')->fetchAll();
$klas=$pdo->query('SELECT klasifikasi_id,kode_klasifikasi,nama_klasifikasi FROM klasifikasi_arsip ORDER BY kode_klasifikasi')->fetchAll();
$s=$pdo->prepare('SELECT nama_unit FROM unit_kerja WHERE unit_id=:u');
$s->execute(['u'=>$unit]);
$unitName=(string)$s->fetchColumn();
$s=$pdo->prepare('SELECT r.ruangan_id,r.nama_ruangan,l.lemari_id,COALESCE(l.nama_lemari,l.kode_lemari) nama_lemari,k.rak_id,k.kode_rak FROM ruangan r JOIN lemari l ON l.ruangan_id=r.ruangan_id JOIN rak k ON k.lemari_id=l.lemari_id WHERE r.unit_id=:u ORDER BY r.nama_ruangan,l.kode_lemari,k.kode_rak');
$s->execute(['u'=>$unit]);
$locations=$s->fetchAll();
$selectedRoom=0;
$selectedCabinet=0;
$selectedRack=(int)($edit['rak_id']??0);
$lastRoom=0;
$lastCabinet=0;
foreach($locations as $location){if((int)$location['rak_id']===$selectedRack){$selectedRoom=(int)$location['ruangan_id'];$selectedCabinet=(int)$location['lemari_id'];break;}}
$q=trim((string)($_GET['q']??''));
$s=$pdo->prepare('SELECT a.*,j.nama_jenis,k.nama_klasifikasi FROM arsip a JOIN jenis_surat j ON j.jenis_surat_id=a.jenis_surat_id LEFT JOIN klasifikasi_arsip k ON k.klasifikasi_id=a.klasifikasi_id WHERE a.unit_id=:u AND (a.no_registrasi LIKE :q1 OR a.no_surat LIKE :q2 OR a.perihal LIKE :q3) ORDER BY a.created_at DESC');
$s->execute(['u'=>$unit,'q1'=>"%$q%",'q2'=>"%$q%",'q3'=>"%$q%"]);
$items=$s->fetchAll();
?>
<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><?php require dirname(__DIR__,2).'/includes/favicon.php';
?><title>Arsip Digital | e-ARSIP</title><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Material+Symbols+Outlined" rel="stylesheet"><link rel="stylesheet" href="assets/css/auth.css"></head><body class="dashboard-body"><aside class="admin-sidebar"><div class="brand"><img src="assets/images/logo_kai.svg" alt="KAI"><div><strong>e-ARSIP</strong><strong>KAI DIVRE III</strong></div></div><nav><p>Petugas Unit</p><a href="dashboard.php?role=petugas">Dashboard</a><span class="nav-active">Arsip Digital</span><a href="jadwal-pemusnahan.php">Jadwal Pemusnahan</a></nav></aside><div class="admin-main"><header class="admin-header"><b>Arsip Digital</b><details class="user-menu"><summary><span class="user-avatar"><?=e(strtoupper(substr((string)($_SESSION['nama_lengkap'] ?? $_SESSION['username'] ?? 'U'),0,1)))?></span><span class="user-summary-text"><b><?=e((string)($_SESSION['nama_lengkap'] ?? $_SESSION['username'] ?? 'User'))?></b><small><?=e((string)($_SESSION['role_name'] ?? 'Petugas'))?></small></span><i class="user-summary-chevron material-symbols-outlined">expand_more</i></summary><div class="user-dropdown"><div class="user-dropdown-header"><b><?=e((string)($_SESSION['nama_lengkap'] ?? $_SESSION['username'] ?? 'User'))?></b><small><?=e((string)($_SESSION['role_name'] ?? 'Petugas'))?></small></div><a href="logout.php"><i class="material-symbols-outlined">logout</i>Logout</a></div></details></header><main class="admin-content"><?php if($notice):?><p class="notice"><?=e($notice)?></p><?php endif;
if($errors):?><div class="alert"><?php foreach($errors as $e):?><div><?=e($e)?></div><?php endforeach;
?></div><?php endif;
?><section class="panel master-form"><h2><?=$edit?'Edit':'Tambah'?> Arsip</h2><form method="post" class="admin-form"><input type="hidden" name="csrf_token" value="<?=e(csrfToken())?>"><input type="hidden" name="action" value="<?=$edit?'update':'create'?>"><?php if($edit):?><input type="hidden" name="arsip_id" value="<?=(int)$edit['arsip_id']?>"><?php endif;
?><label>No Registrasi<input name="no_registrasi" required value="<?=e($edit['no_registrasi']??'')?>" <?=$edit?'readonly':''?>></label><label>No Surat<input name="no_surat" required value="<?=e($edit['no_surat']??'')?>"></label><label>Perihal<input name="perihal" required value="<?=e($edit['perihal']??'')?>"></label><label>Tanggal Surat<input type="date" name="tanggal_surat" required value="<?=e($edit['tanggal_surat']??'')?>"></label><label>Jenis Surat<select name="jenis_surat_id" required><?php foreach($jenis as $x):?><option value="<?=(int)$x['jenis_surat_id']?>" <?=((int)($edit['jenis_surat_id']??0)===(int)$x['jenis_surat_id'])?'selected':''?>><?=e($x['nama_jenis'])?></option><?php endforeach;
?></select></label><label>Klasifikasi<select name="klasifikasi_id"><option value="">-</option><?php foreach($klas as $x):?><option value="<?=(int)$x['klasifikasi_id']?>" <?=((int)($edit['klasifikasi_id']??0)===(int)$x['klasifikasi_id'])?'selected':''?>><?=e($x['kode_klasifikasi'].' - '.$x['nama_klasifikasi'])?></option><?php endforeach;
?></select></label><label>Unit Kerja<input value="<?=e($unitName)?>" readonly></label><label>Ruangan<select id="ruangan_id"><option value="">Pilih ruangan</option><?php foreach($locations as $x):if((int)$x['ruangan_id']!==$lastRoom):$lastRoom=(int)$x['ruangan_id'];?><option value="<?=$lastRoom?>" <?=$selectedRoom===$lastRoom?'selected':''?>><?=e($x['nama_ruangan'])?></option><?php endif;endforeach;?></select></label><label>Lemari<select id="lemari_id"><option value="">Pilih lemari</option><?php foreach($locations as $x):if((int)$x['lemari_id']!==$lastCabinet):$lastCabinet=(int)$x['lemari_id'];?><option value="<?=$lastCabinet?>" data-room="<?=(int)$x['ruangan_id']?>" <?=$selectedCabinet===$lastCabinet?'selected':''?>><?=e($x['nama_lemari'])?></option><?php endif;endforeach;?></select></label><label>Rak<select id="rak_id" name="rak_id"><option value="">-</option><?php foreach($locations as $x):?><option value="<?=(int)$x['rak_id']?>" data-cabinet="<?=(int)$x['lemari_id']?>" <?=((int)($edit['rak_id']??0)===(int)$x['rak_id'])?'selected':''?>><?=e($x['kode_rak'])?></option><?php endforeach;
?></select></label><label>Status<select name="status_arsip"><?php foreach(['Aktif','Permanen','Musnah'] as $x):?><option <?=$x===($edit['status_arsip']??'Aktif')?'selected':''?>><?=$x?></option><?php endforeach;
?></select></label><label>Masa Simpan Tahun<input type="number" min="0" name="masa_simpan_tahun" value="<?=e((string)($edit['masa_simpan_tahun']??''))?>"></label><label>Mulai Retensi<input type="date" name="tanggal_mulai_retensi" value="<?=e($edit['tanggal_mulai_retensi']??'')?>"></label><label>Jatuh Tempo<input type="date" name="tanggal_jatuh_tempo" value="<?=e($edit['tanggal_jatuh_tempo']??'')?>"></label><label>Detail<textarea name="detail_arsip"><?=e($edit['detail_arsip']??'')?></textarea></label><label>Keterangan<textarea name="keterangan"><?=e($edit['keterangan']??'')?></textarea></label><div><button class="primary-button">Simpan</button></div></form></section><?php if($edit):$files=$pdo->prepare('SELECT file_id,nama_file,ekstensi,ukuran_file,is_primary,uploaded_at FROM file_arsip WHERE arsip_id=:id ORDER BY uploaded_at DESC');
$files->execute(['id'=>(int)$edit['arsip_id']]);
$files=$files->fetchAll();
?><section class="panel"><h2>File Dokumen</h2><div class="table-wrap"><table><thead><tr><th>Nama File</th><th>Ukuran</th><th>Tipe</th><th>Primary</th><th>Upload</th><th>Aksi</th></tr></thead><tbody><?php foreach($files as $file):?><tr><td><?=e($file['nama_file'])?></td><td><?=(int)$file['ukuran_file']?> bytes</td><td><?=e($file['ekstensi']??'-')?></td><td><?=(int)$file['is_primary']?'Ya':'Tidak'?></td><td><?=e($file['uploaded_at'])?></td><td><a href="download-arsip.php?id=<?=(int)$file['file_id']?>">Download</a></td></tr><?php endforeach;
?><?php if(!$files):?><tr><td colspan="6">Belum ada file dokumen.</td></tr><?php endif;
?></tbody></table></div><form method="post" action="upload-arsip.php" enctype="multipart/form-data" class="admin-form"><input type="hidden" name="csrf_token" value="<?=e(csrfToken())?>"><input type="hidden" name="arsip_id" value="<?=(int)$edit['arsip_id']?>"><label>Pilih File<input type="file" name="document" accept=".pdf,.jpg,.jpeg,.png" required></label><p>Maksimal 20 MB per file. Format: PDF, JPG, JPEG, PNG.</p><button class="primary-button" type="submit">Upload</button></form></section><?php endif;
?><section class="panel user-list"><h2>Daftar Arsip</h2><form class="filter-form"><input name="q" value="<?=e($q)?>" placeholder="Registrasi, surat, perihal"><button>Cari</button></form><div class="table-wrap"><table><thead><tr><th>Registrasi</th><th>Surat</th><th>Perihal</th><th>Jenis</th><th>Status</th><th>Aksi</th></tr></thead><tbody><?php foreach($items as $x):?><tr><td><?=e($x['no_registrasi'])?></td><td><?=e($x['no_surat'])?></td><td><?=e($x['perihal'])?></td><td><?=e($x['nama_jenis'])?></td><td><?=e($x['status_arsip'])?></td><td><a href="arsip.php?edit=<?=(int)$x['arsip_id']?>">Edit</a> <a class="detail-link" href="arsip-detail.php?id=<?=(int)$x['arsip_id']?>">Detail</a></td></tr><?php endforeach;
?></tbody></table></div></section><div id="detail-modal" hidden style="position:fixed;inset:0;background:rgba(0,0,0,.55);z-index:1000;padding:2rem;overflow:auto"><section role="dialog" aria-modal="true" aria-label="Detail Arsip" style="background:#fff;margin:auto;max-width:960px;min-height:80vh;position:relative"><button id="detail-close" type="button" aria-label="Tutup" style="position:absolute;right:.75rem;top:.75rem;z-index:1">×</button><iframe id="detail-frame" title="Detail Arsip" style="border:0;width:100%;min-height:80vh"></iframe></section></div></main></div><script>const modal=document.getElementById('detail-modal'),frame=document.getElementById('detail-frame'),closeModal=()=>{modal.hidden=true;frame.removeAttribute('src');};document.querySelectorAll('.detail-link').forEach(link=>link.addEventListener('click',event=>{event.preventDefault();frame.src=link.href;modal.hidden=false;}));document.getElementById('detail-close').onclick=closeModal;modal.onclick=event=>{if(event.target===modal)closeModal();};document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!modal.hidden)closeModal();});const room=document.getElementById('ruangan_id'),cabinet=document.getElementById('lemari_id'),rack=document.getElementById('rak_id');function filter(select,key,value){for(const option of select.options)if(option.value)option.hidden=option.dataset[key]!==value;}function rooms(){filter(cabinet,'room',room.value);if(cabinet.selectedOptions[0]?.hidden)cabinet.value='';cabinets();}function cabinets(){filter(rack,'cabinet',cabinet.value);if(rack.selectedOptions[0]?.hidden)rack.value='';}room.onchange=rooms;cabinet.onchange=cabinets;rooms();</script></body></html>